INSERT INTO `country` (`id`, `code`, `name`) VALUES
(1, 'es', 'España');

INSERT INTO `company` (`id`, `country_id`, `vat`, `name`, `deleted`) VALUES
(1, '1', 'R2464781J', 'GENERES SA', '0');


INSERT INTO `user` (`id`, `company_id`, `email`, `first_name`, `last_name`, `deleted`, `roles`, `password`) VALUES
(1, NULL, 'user@user.com', 'JUSTO', 'HEREDIA VELA', '0', '[\"ROLE_CANDIDATE\"]', '$argon2id$v=19$m=65536,t=4,p=1$sRxdQ1qVpYG85Zn/WupOyw$kYDhpXhKF0egInhGBj9WdE5yg9AEi5DKiu26+YECWoY'),
(2, NULL, 'company@company.com', 'LUIS ALBERTO', 'SAEZ VENTURA', '0', '[\"ROLE_COMPANY\"]', '$argon2id$v=19$m=65536,t=4,p=1$sRxdQ1qVpYG85Zn/WupOyw$kYDhpXhKF0egInhGBj9WdE5yg9AEi5DKiu26+YECWoY');

INSERT INTO `job_offer` (`id`, `company_id`, `user_id`, `code`, `name`, `description`, `publication_date`, `job_start_date`, `job_end_date`, `vacancies`, `deleted`) VALUES
(1, '1', '2', '104ab42f', 'Mantenimiento agrícola', '<p>Para importante empresa del sector agrario estamos buscando un peón agrícola de mantenimiento (H/M) para realizar reparaciones de sistema de riego, mantenimiento de las instalaciones de la finca en general y de alambrados.</li></ul>', '2021-05-16 16:34:10.000000', '2021-07-01 16:34:10.000000', '2021-09-31 16:34:10.000000', '2', '0'),
(2, '1', '2', '104ab42f', 'Vendimia ', '<p>La cosecha de las uvas para el vino, se realiza en nuestro territorio entre julio y octubre, dependiendo de las condiciones climáticas, de la zona de producción, el tipo de uva y el tipo de vino que se quiera obtener.</p>', '2021-05-16 16:34:10.000000', '2021-07-01 16:34:10.000000', '2021-09-31 16:34:10.000000', '6', '0'),
(3, '1', '2', '104ab42f', 'Peón agrícola', '<p>Se necesita peón agrícola para la realización de diversas tareas del campo, como recogida o recoleccion de aceituna, quitar varetas o poda de olivar. Disponemos de maquinaria y vehículo propios.</p>', '2021-05-16 16:34:10.000000', '2021-07-01 16:34:10.000000', '2021-09-31 16:34:10.000000', '1', '0'),
(4, '1', '2', '104ab42f', 'Siembra', '<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p><p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', '2021-05-16 16:34:10.000000', '2021-07-01 16:34:10.000000', '2021-09-31 16:34:10.000000', '3', '0'),
(5, '1', '2', '104ab42f', 'Recolección', '<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p><p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using ''Content here, content here'', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for ''lorem ipsum'' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>', '2021-05-16 16:34:10.000000', '2021-07-01 16:34:10.000000', '2021-09-31 16:34:10.000000', '3', '0');
