version: '3.5'

services:
  app:
    build: .
    volumes:
      - ./sandbox/:/app
    working_dir: /app

  webserver:
    image: nginx:latest
    ports:
      - 8001:80
    volumes:
      - ./etc/infrastructure/nginx/conf.d/:/etc/nginx/conf.d/

  db:
    image: mysql:5.5.43
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sandbox
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8002:80
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      PMA_HOST: db
    depends_on:
      - db

volumes:
  db-data:
