version: '3.5'

services:
  app:
    build: .
    volumes:
      - ./sandbox/:/app
    working_dir: /app

  webserver:
    image: nginx:latest
    ports:
      - 8091:80
    volumes:
      - ./etc/infrastructure/nginx/conf.d/:/etc/nginx/conf.d/

  db:
    image: mysql:5.5.43
    ports:
      - 3396:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sandbox
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
